### ISSUE TITLE
Captcha display but not working

### ISSUE THREAD

**Issue by killday** [mageplaza/magento-2-google-recaptcha#39] opened 2019-11-13 13:29 UTC
It let you log in even if you don't click or pass the captcha. I have installed the library but I have already register.php in lib folder for the Browser Detection so I didn't copy the file. How should I install the library in that case ?
![image](https://user-images.githubusercontent.com/6714294/68768027-a62ae700-0619-11ea-8888-691aa4154a97.png)

**Comment by Arthas7895** [comment] 2019-11-14 02:57
First, thank you for your information. We checked it out and found it as you described. 
Regarding the 'no click captcha but still submit form' issue, you can download and replace the attached file with the link
where you install the Google Recaptcha module\Observer\Captcha.php
Here is the download file link
https://drive.google.com/file/d/1e9PCKEB95pNwHKKGOmkXugCoVqbSEPjy/view?usp=sharing
Regarding the second problem, I can confirm that you have installed the lib in the correct path

**Comment by killday** [comment] 2019-11-14 15:54
Hi unfortunately that doesn't work too. On the front end can't post the form even the captcha is passed (It may be because I got two forms on same page). On the back end admin login with or without passed captcha. 
Magento 2.2.0

**Comment by killday** [comment] 2019-11-26 12:00
Any change or news on that issue?

**Comment by killday** [comment] 2019-12-10 08:52
Any help or I have to swich to another extesion?

**Comment by Arthas7895** [comment] 2019-12-19 04:23
If you are using a custom form in addition to the front end, make sure you have filled out the CSS Selectors field in the backend.
Regarding the captcha problem in the backend, you can download and replace the following file according to the link 
Where have you installed GoogleRecaptcha module\Observer\Adminhtml\Login.php
[Login.zip](https://github.com/mageplaza/magento-2-google-recaptcha/files/3981713/Login.zip)

**Comment by Arthas7895** [comment] 2019-12-26 10:20
Since I haven't received any response from you in the past 7 days, I will close this issue here
Thank you!

**Closed by Arthas7895** 2019-12-26 10:20 UTC

**Comment by killday** [comment] 2020-02-21 10:15
Sorry for the late answer, I can confirm that now all work properly. Thnaks.
