### ISSUE TITLE
Serialization error after upgrading to 4.0.2

### ISSUE THREAD

**Issue by wurstsalat3000** [mageplaza/magento-2-google-recaptcha#66] opened 2021-08-05 11:44 UTC
Hi! After upgrading the extension to 4.0.2, I experienced the following error (which completely prevents the site from loading):

```
{
"0":"Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded","1":"#1 Magento\\Framework\\App\\PageCache\\Kernel->process() called at [generated\/code\/Magento\/Framework\/App\/PageCache\/Kernel\/Interceptor.php:32]\n

#2 Magento\\Framework\\App\\PageCache\\Kernel\\Interceptor->process() called at [vendor\/magento\/module-page-cache\/Model\/Controller\/Result\/BuiltinPlugin.php:96]\n

#3 Magento\\PageCache\\Model\\Controller\\Result\\BuiltinPlugin->afterRenderResult() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:146]\n

#4 Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n

#5 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php:95]\n

#6 Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult() called at [vendor\/magento\/framework\/App\/Http.php:120]\n

#7 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n

#8 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:263]\n

#9 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/","script_name":"\/pub\/index.php","report_id":"xxx"}
```

Magento version: 2.4.2-p1

This error does not occur if I disable the extension.

I guess this is related to recent changes around encrypting API keys. Please let me know if you need additional details.

**Comment by HuyPhuc98** [comment] 2021-08-09 04:42
Hi,

The cause of your problem may be that the latest version of the Google Recaptcha module is not compatible with the new Magento 2.4.2-p1.
I will check this issue and will notify you when the results are available.

Before that, for the module to work properly, you can downgrade the Google Recaptcha version to version 4.0.0 and try again for me.
Thank you!

**Comment by wurstsalat3000** [comment] 2021-08-13 08:49
I can confirm that downgrading to Google Recaptcha 4.0.0 works as expected (now with Magento 2.4.2-p2 as well).

**Comment by HuyPhuc98** [comment] 2021-08-13 10:01
Hi,

Thanks for your feedback, we are still in the process of trying to find a solution to update the Google Recaptcha module with the latest version to be compatible with Magento 2.4.2-p1.
It will be released in the near future.

Thank you!

**Comment by HuyPhuc98** [comment] 2021-08-31 03:11
We will close this issue due no response within 7 days

**Closed by HuyPhuc98** 2021-08-31 03:11 UTC

**Comment by wurstsalat3000** [comment] 2021-08-31 16:47
Did you expect a response from me?

Has this issue been fixed in a newer version?

**Comment by wurstsalat3000** [comment] 2021-09-08 10:08
Since there has been no new release since 4.0.2, the problem described is still persistent.

Please re-open this issue.

**Comment by samcleathero** [comment] 2021-09-14 15:32
This issue is a result of Mageplaza updating the config values in the module to be encrypted, without any sort of function to ensure existing unencrypted values are "upgraded" to be encrypted, meaning Magento attempts to decrypt already unencrypted values.

@HuyPhuc98 - I can't understand why this issue has been closed with no resolution when this issue completely breaks sites after a module upgrade. Could you please re-open this issue and treat this as a critical problem?

@wurstsalat3000 (and anyone else with this issue) - A workaround is to use [n98-magerun2](https://github.com/netz98/n98-magerun2) to set the encrypted values after upgrading the module.
`n98-magerun2.phar config:store:set --encrypt googlerecaptcha/general/invisible/api_key INVISIBLE_SITE_KEY`
`n98-magerun2.phar config:store:set --encrypt googlerecaptcha/general/invisible/api_key INVISIBLE_SECRET_KEY`
`n98-magerun2.phar config:store:set --encrypt googlerecaptcha/general/visible/api_key VISIBLE_SITE_KEY`
`n98-magerun2.phar config:store:set --encrypt googlerecaptcha/general/visible/api_key VISIBLE_SECRET_KEY`
